version: "3"

services:
    banco_app:
        build:
            context: .
            dockerfile: Dockerfile_app
        command:
            sh -c "cd banco && python manage.py runserver 0.0.0.0:8000"
    recibo_app:
        build:
            context: .
            dockerfile: Dockerfile_app
        command:
            sh -c "cd recibo && python manage.py runserver 0.0.0.0:8002"
    mytoxiproxy:
        image: shopify/toxiproxy
        ports:
         - "22220:22220"
         - "22222:22222"
         - "8474:8474"
    mytoxiproxy-configurer:
        build:
            context: .
            dockerfile: Dockerfile-toxiproxy-configurer
        depends_on:
            - mytoxiproxy
